language: php

sudo: required

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  - nightly

install:
  - travis_retry composer install --no-interaction

matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm
        - php: nightly

script:
  - phpunit --no-coverage